language: ruby
rvm:
- 2.2.1

before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

script: rake travis

deploy:
  provider: heroku
  api_key:
    secure: l2z4sKgybC58rYW5te5KnE+kUzQnZ7KvJSergM/wYNPsgtFU2bRfhNzsqyR6ttB/mvLJWxCYVpej9gLSYAY+jQs/g50a8bQgE9zUCmqZz97j2R62AQ+HfERpIHhQv8XhpNWRSUyzxql/fRxoa2zo1c1V8WkdiLvvbZELlqC08xWZvu91Ux86JoT6HMdF0APmD+3Vv1Vu6JOpZYENdOEszQ/lHGyBmxIAVi5RsU/RFalbXyMdmaQXI/sYsvoqm7gg7P/dJf53T8pAuVpXI7QR4x9OuG2QwWOvezyQTLebbZdAAgNYWb2A2udlEg4dxcXR70ASorcNpP+W8Hy68ejdhDEz+K/CtAIkucS23zbUQVj9p0eolGUIGTXjHZ8l5Gy/sTDNDYlYVteM7alN8uneJXSiBe2BuKcvQErLZM05Hig3oSRdFB9RWZtzCK0pylfTQO6UXMa9n/friV8lLuzW3IzpZf0IWQHuEaRwez7x3WEZaihZBt/pU3N+1mXVZW0EavIkNLe5hrkR9N7Go+8VpZrmIsQzHYbZRI3ZNxxSavFhfUqwwBmrbIuthlCd1GnDYd/qFBKz0HIdpTdaQwldoaQpcjJrGN/n/biEThObZEHpux9UivS0hwVMcy2KKxcVkxifJncWnzO0xITAVlKxest6Rwq9r6736ZiOctam3Cc=
  app: samjones-uicalc
  on:
    repo: samlawrencejones/uicalc
